### ISSUE TITLE
docker-compose-withDtAppMon.yml does not match Dynatrace-AppMon-Docker project

### ISSUE THREAD

**Issue by mpvvliet** [Dynatrace/easyTravel-Docker#3]
I'm trying to get the dockerized version of AppMon to work with easyTravel-Docker as per the instructions. I've successfully setup Dynatrace-AppMon-Docker and can run it in docker.

Unfortunately, the command `docker-compose -f docker-compose-withDtAppMon.yml up` fails because the links to the AppMon docker setup (networks, volumes) do not match. I've tried porting the configuration file to v3 and fixing the links, but have been unable to get it working.

Any help would be much appreciated.

Thanks,
Martin

**Comment by savishy** [comment]
Here are the modifications I made to get the Composefile to interact with the Dynatrace Server from `Dynatrace-AppMon-Docker`. With these modifications, Easy Travel data is logged in Dynatrace. Hope it helps.

* External Network `dynatracedocker_appmon` (in my case this is the network created by the Dynatrace Server Compose stack).
* External Volume `dynatracedocker_dthome` (I modified Dynatrace Compose file to create Docker Volumes per the latest versions of Docker). 
* Service names match host names and container names (otherwise I was getting `getaddrinfo host not found` errors.

```
version: "3.0"
services:
  easytravel-mongodb:
    hostname: easytravel-mongodb
    container_name: easytravel-mongodb
    image: "dynatrace/easytravel-mongodb"
    ports:
    - 27017
    - 28017

  easytravel-backend:
    hostname: easytravel-backend
    container_name: easytravel-backend
    image: "dynatrace/easytravel-backend"
    ports:
    - 8080
    links:
    - easytravel-mongodb
    volumes:
    - dynatracedocker_dthome:/dynatrace
    environment:
      CATALINA_OPTS: "-agentpath:/dynatrace/agent/lib64/libdtagent.so=name=BusinessBackend_easyTravel,collector=dtcollector"
      ET_DATABASE_LOCATION: "easytravel-mongodb:27017"

  easytravel-frontend:
    hostname: easytravel-frontend
    container_name: easytravel-frontend
    image: "dynatrace/easytravel-frontend"
    ports:
    - 8080
    links:
    - easytravel-backend
    - easytravel-mongodb
    volumes:
    - dynatracedocker_dthome:/dynatrace
    environment:
      CATALINA_OPTS: "-agentpath:/dynatrace/agent/lib64/libdtagent.so=name=CustomerFrontend_easyTravel,collector=dtcollector"
      ET_BACKEND_URL: "http://easytravel-backend:8080"

  easytravel-www:
    hostname: easytravel-www
    container_name: easytravel-www
    image: "dynatrace/easytravel-nginx"
    ports:
    - 80
    links:
    - easytravel-frontend
    - easytravel-backend
    volumes:
    - dynatracedocker_dthome:/dynatrace
    environment:
      ET_FRONTEND_LOCATION: "easytravel-frontend:8080"
      ET_BACKEND_LOCATION: "easytravel-backend:8080"
      DT_AGENT_NAME: "WebServer_easyTravel"
      DT_AGENT_COLLECTOR: "dtcollector"
      LD_PRELOAD: "/dynatrace/agent/lib64/libdtagent.so"
    command: sh -c "/dynatrace/run-wsagent.sh && /run-process.sh"

  loadgen:
    container_name: loadgen
    image: "dynatrace/easytravel-loadgen"
    links:
    - easytravel-backend
    - easytravel-frontend
    - easytravel-www
    environment:
      ET_FRONTEND_URL: "http://easytravel-www:80"
      ET_BACKEND_URL: "http://easytravel-www:8080"
      ET_PROBLEMS: "BadCacheSynchronization,CPULoad,DatabaseCleanup,DatabaseSlowdown,FetchSizeTooSmall,JourneySearchError404,JourneySearchError500,LoginProblems,MobileErrors,TravellersOptionBox"

networks:
  default:
    external:
      name: dynatracedocker_appmon

volumes:
  dynatracedocker_dthome:
    external: true
```
