### ISSUE TITLE
Persistent Hourly Authentication and CPU problems when ET_PROBLEMS are disabled

### ISSUE THREAD

**Issue by BraydenNeale** [Dynatrace/easyTravel-Docker#6]
```yaml 
loadgen:
  container_name: loadgen
  image: "dynatrace/easytravel-loadgen"
  links:
  - backend
  - frontend
  - www
  environment:
    ET_APM_SERVER_DEFAULT: "${ET_APM_SERVER_DEFAULT}"
    ET_FRONTEND_URL: "http://easytravel-www:80"
    ET_BACKEND_URL: "http://easytravel-www:8080"
    ET_PROBLEMS: ""
```

`ET_PROBLEMS: ""`
Every hour there are authentication problems and CPU problems.
Based on this yml config no problems should be present in our easyTravel deployment.
This is conflicting with problems we are manually simulating and remediating
